### PR TITLE
Back out changes to rust-hdf5.

### PR DESCRIPTION
**Pull request by adam-azarchs**
Yeah, might not work on Windows.  We can address that properly later,
but for now the important thing is not breaking dependabot for
downstream users by having multiple sources for hdf5-sys.

Also, add a dependabot config.

### CODE REVIEW

**Comment by nmmsv10x** [comment]
Clippy is clobbering the diff view, would it be possible to disable it? It would make reviewing this PR and future dev much more doable.

**Comment by adam-azarchs** [comment]
> Clippy is clobbering the diff view, would it be possible to disable it? It would make reviewing this PR and future dev much more doable.

Absolutely not.  More likely is we'll switch those lints to `deny` level to make sure those bugs get fixed at high priority.

**Comment by sjackman** [comment]
> Clippy is clobbering the diff view, would it be possible to disable it? It would make reviewing this PR and future dev much more doable.

https://twitter.com/natfriedman/status/1366417484698578953

> We've just shipped a shortcut that might help with your code reviews on GitHub this week: press 'a' to toggle annotations and reduce the clutter.

**Review by sjackman — APPROVED** [review]
Looks good to me!

**Pull request merged**
